<div style="color:darkgreen;background-color:lightgreen;padding:10px">

# <center>Assignment 1</center>

<div style="font-size: 1.3em; color:red;padding-top:10px"><center></center></div>
</div>

</div>

## Instructions
1. Create a Jupyter notebook, using this file as the skeleton
1. Please add extra code or markdown cells as needed for clarity and formatting
1. You may be able to use the Labs, homeworks or practice exercises as samples to work out the solutions
1. Please do not copy files from your classmates, or cut and paste
1. Before submitting, make sure that everything recomputes properly
    - Save and close the Jupyter notebook, restart *SageMath* and load the file again
    - Clear all output from **Cell >> All Output >> Clear**
    - Repopulate everything by  **Cell >> Run All**
    - Check carefully to ensure that all answers are computed correcly
1. Rename your file using your name, like: `manoj-A1.ipynb`
1. Submit to **eLearn >> Assignments >> Assignment 1** folder
    - You can submit as many times as you want, but only the last submission will be retained and graded
    - To be clear, the previous versions will be *overwritten*
    - All submissions are timestamped, and late submissions will be penalized
    - After a short grace period, the Assignment folder will be locked
    - Please do not try to submit by email or any other means

## Valuation
Assignment will be graded using the following criteria
   - 70% : Correctness
   - 10% : Brevity and elegance of the solutions
   - 10% : Clarity and formatting
   - 10% : Creativity  
Do not ask us to specify what creativity is. If we were to specify it, it wouldn't be *creativity*, but *instructions*!

## Hints
   - Some of the questions require data entry, like defining matrices in **Q1**. In order to help you avoid typos, I have provided the numbers that can be copied and pasted.
   - The names of the matrices and vectors (as in $Ax=b$) may be repeated between questions. In order to avoid using a wrong matrix (e.g., $A$ in **Q1** reused in **Q2**), I recommend you use `A1` ($A_1$) for **Q1**,  `A2` ($A_2$) for **Q2** and so on.
   - In many places, you will be asked to compare answers. Wherever possible, the comparison should be done using `==` and answer should be printed out.  
Example: Compare a and b: `print("Is a equal to b? ", a == b)`
  


<div style="color:darkgreen;background-color:lightgreen;padding:10px">


# Question 1
<div style="text-align: right; font-size: 1.3em; color:red"> Total 10 Marks for Q1</div>
</div>

### 1(a)
<div style="text-align: right; font-size: 1.1em; color:red"> [2 marks]</div>

Check whether the three vectors given below are linearly independent. If not, find the relationship between these vectors.
$$ x_1 = \left(\begin{array}{r}
1 \\
1 \\
0
\end{array}\right)
\qquad x_2 =
\left(\begin{array}{r}
0 \\
1 \\
2
\end{array}\right)
\qquad x_3 =
\left(\begin{array}{r}
3 \\
1 \\
-4
\end{array}\right)$$

`Vectors: (1, 1, 0), (0, 1, 2), (3, 1, -4)`

In [70]:
#Create vectors x1, x2, x3
x1 = vector([1, 1, 0])
x2 = vector([0, 1, 2])
x3 = vector([3, 1, -4])

#Create matrix A composed of vectors x1, x2, x3
A = matrix(QQ, [x1, x2, x3])

#Show matrix A
pretty_print("matrix A :", A)

#Show rank of matrix A
pretty_print("Rank of matrix A :", A.rank())

'matrix A :' [ 1  1  0]
[ 0  1  2]
[ 3  1 -4]

'Rank of matrix A :' 2

No, the three vectors given are not linearly independent.

The rank of A is 2, this indicates that A is not a full-rank matrix and there are only 2 (out of 3) linearly independent equations. In other words, there is one linearly dependent equation.

In [71]:
#Find the scalars s1, s2 to show the linear dependency
var('s1, s2')
eq_1 = 1*s1 + 0*s2 == 3
eq_2 = 1*s1 + 1*s2 == 1
eq_3 = 0*s1 + 2*s2 == -4

#Solve the equations to obtain s1, s2
pretty_print(str(solve([eq_1, eq_2, eq_3], s1, s2))[3:-3])

marks = 0
marks += 2

's1 == 3, s2 == -2'

By solving the equations, we have s1 = 3, s2 = -2, such that (s1 * x1) + (s2 * x2) = x3. This implies that x3 is linearly dependent on x1 and x2 because it is, in fact, a linear combination of them.

### 1(b)
<div style="text-align: right; font-size: 1.1em; color:red"> [2 marks]</div>

Here is a matrix $A$.
$$ A =  \left(\begin{array}{rr}
1 & 0 & 0 \\
2 & 3 & 0 \\
3 & 1 & 2
\end{array}\right) $$

Express vector $x$ as a linear combination of the column vectors of $A$.
$$ x = \left(\begin{array}{r}
1 \\
1 \\
2
\end{array}\right) $$

`A: [(1, 0, 0), (2, 3, 0), (3, 1, 2)]` 
`x: (1, 1, 2)`

In [72]:
#Create matrix A
A = matrix([[1, 0, 0], [2, 3, 0], [3, 1, 2]])

#Create vector x
x = vector([1, 1, 2])

#Create augmented matrix A_aug, composed of coefficient matrix A, and constant x
A_x_aug = A.augment(x, subdivide = true)

#Perform Gauss-Jordan Elimination to obtain RREF of A_aug
pretty_print("RREF of A_aug: ")
pretty_print(A_x_aug.rref())

'RREF of A_aug: '

[   1    0    0|   1]
[   0    1    0|-1/3]
[   0    0    1|-1/3]

Let $a1, a2, a3$ be the columns of coefficient matrix A, from left to right. Then, we observe the column picture as below:

In [73]:
#Create the column vectors a1, a2, a3
a1 = vector([1, 2, 3])
a2 = vector([0, 3, 1])
a3 = vector([0, 0, 2])

#Verify the results of column picture with x
pretty_print("vector x = ", x)
pretty_print("Expression vector x as linear combination of the column vectors of A : 1*a1 - (1/3)*a2 - (1/3)*a3 = ", 1*a1 - (1/3)*a2 - (1/3)*a3, " = x")
marks += 2

'vector x = ' (1, 1, 2)

'Expression vector x as linear combination of the column vectors of A : 1*a1 - (1/3)*a2 - (1/3)*a3 = ' (1, 1, 2) ' = x'

### 1(c)
<div style="text-align: right; font-size: 1.1em; color:red"> [1 mark]</div>

Here is another matrix $B$.
$$ B =  \left(\begin{array}{rr}
-1 & 2 & 13 \\
14 & 3 & -1 \\
1 & 4 & 0
\end{array}\right) $$

Check whether ($A$$B$)$A$ = $A$($B$$A$) and $(AB)^2$ = $A^2$$B^2$

`B: [(-1, 2, 13), (14, 3, -1), (1, 4, 0)]` 

In [74]:
#Create matrix B
B = matrix([[-1, 2, 13], [14, 3, -1], [1, 4, 0]])

#Check if the statements are true
pretty_print("Is (AB)A equals to A(BA)? : ", (A * B) * A == A * (B * A))
pretty_print("Is Equation (AB)^2 equals to (A^2)(B^2)? :", (A * B) ** 2 == (A ** 2) * (B ** 2))

marks += 1

'Is (AB)A equals to A(BA)? : ' True

'Is Equation (AB)^2 equals to (A^2)(B^2)? :' False

### 1(d)
<div style="text-align: right; font-size: 1.1em; color:red"> [2 marks]</div>

Is $B$ singular? Is it skew-symmetric? If not, find a possible skew-symmetric matrix using $B$?

In [75]:
#Get the determinant of matrix B for singularity check
pretty_print("Is B singular? (determinant of matrix B equals to 0) :", B.det() == 0)

#Check if the matrix B is skew-symmetric
pretty_print("Is skew-symmetric? (B^T == -B) :", B.T == -B)

'Is B singular? (determinant of matrix B equals to 0) :' False

'Is skew-symmetric? (B^T == -B) :' False

The first result indicates that B has a non-zero determinant. Hence, matrix B is not a singular matrix.

The second result indicates that B is not a skew-symmetric matrix by performing a simple test, i.e., taking transpose of B and check if that is equal to negative of B.

In [76]:
#Create a skew-symmetric matrix using B
pretty_print("Skew-symmetric matrix made based on matrix B :")
pretty_print(B - B.T)

marks += 2

'Skew-symmetric matrix made based on matrix B :'

[  0 -12  12]
[ 12   0  -5]
[-12   5   0]

This creates a skew-symmetric matrix based on B, i.e., by taking B minus transpose of B.

### 1(e)
<div style="text-align: right; font-size: 1.1em; color:red"> [1 mark]</div>

What is $A(A^{-1}+B^{-1})B(A+B)^{-1}A^T$?

In [77]:
#Perform computation for ( A * (A^-1 + B^-1) * B * (A + B)^-1 * A^T ) using SageMath
pretty_print("Result of computation: ")
pretty_print(A * (A.inverse() + B.inverse()) * B * (A + B).inverse() * A.T)

marks += 0.8
#can simplify given expression to A.T using properties of inverses

'Result of computation: '

[1 2 3]
[0 3 1]
[0 0 2]

### 1(f)
<div style="text-align: right; font-size: 1.1em; color:red"> [2 marks]</div>

What is $(A^TB)^T$? Illustrate using column picture of matrix multiplication.

Before performing any computation, we can simplify $(A^TB)^T = B^T(A^T)^T = B^TA$. Hence, first show what matrix $B^T$ is, as well as matrix $A$ for reference purpose.

In [78]:
#Show Transpose of matrix B
pretty_print("Matrix B^T : ")
pretty_print(B.T)

#Show matrix A
pretty_print("Matrix A : ")
pretty_print(A)

'Matrix B^T : '

[-1 14  1]
[ 2  3  4]
[13 -1  0]

'Matrix A : '

[1 0 0]
[2 3 0]
[3 1 2]

The column picture of matrix multiplication for $B^TA$ is done by the following step:

(1) Take each column vector in $B^T$, scaled by each scalar in the first column of $A$, the summation of these scaled column vectors gives the first column vector of $B^TA$. 
    
(2) Repeat the first step until all column vectors in $A$ are exhausted (second column and third column) to get the full $B^TA$.

In [79]:
#Select the column vectors in A, as a1(first column), a2(second column), a3(third column) using unit vectors
a1 = A * vector([1, 0, 0])
a2 = A * vector([0, 1, 0])
a3 = A * vector([0, 0, 1])

#Perform matrix-vector multiplication using SageMath, as mentioned in the first step above
#Create vectors for B^T * A, as bt_a1, bt_a2, bt_a3
bt_a1 = B.T * a1
bt_a2 = B.T * a2
bt_a3 = B.T * a3

#Store each vectors as rows in the matrix temp
temp = matrix([bt_a1, bt_a2, bt_a3])

#Convert temp to actual result, i.e., B^T * A
bt_a = temp.T

#Show the result of B^T * using column picture
pretty_print("Result of B^T * A using column picture : ")
pretty_print(bt_a)

marks += 2

'Result of B^T * A using column picture : '

[30 43  2]
[20 13  8]
[11 -3  0]

<div style="color:darkgreen;background-color:lightgreen;padding:10px">


# Question 2
<div style="text-align: right; font-size: 1.3em; color:red"> Total 10 Marks for Q2</div>
</div>

Work with the system of linear equations given below to answer the questions ***2(a) - 2(c)***.
$$ \begin{array}{rr4}
 x + y + z + w &=& 13\\
 2 \, x + 3 \, y - w &=& -1\\
-3 \, x + 4 \, y + z + 2 \, w &=& 10\\
 x + 2 \, y - z + w &=& 1
\end{array}$$
`Eqns: 
 x + y + z + w == 13,
 2*x + 3*y - w == -1,
-3*x + 4*y + z + 2*w == 10,
 x + 2*y -z + w == 1`

### 2(a)
<div style="text-align: right; font-size: 1.1em; color:red"> [1 mark]</div>

If you were to write this system as $A_2x=b_2$, what is the coefficient matrix $A_2$? What is the RHS vector $b_2$?

In [80]:
#Create the matrix A2
A2 = matrix([[1, 1, 1, 1], [2, 3, 0, -1], [-3, 4, 1, 2], [1, 2, -1, 1]])

#Create the RHS vector b2
b2 = vector([13, -1, 10, 1])

#Show the matrix A2 and RHS vector b2
pretty_print("Coefficient matrix A2 : ")
pretty_print(A2)
pretty_print("RHS vector b2 : ", b2)

marks += 1

'Coefficient matrix A2 : '

[ 1  1  1  1]
[ 2  3  0 -1]
[-3  4  1  2]
[ 1  2 -1  1]

'RHS vector b2 : ' (13, -1, 10, 1)

### 2(b)
<div style="text-align: right; font-size: 1.1em; color:red"> [3 marks]</div>

Compute the ***Row Echelon Form*** of the augmented matrix $[A_2|b_2]$ using the row reduction, step-by-step process and ***solve the given equations***.  
(Use only the method `matrix.add_multiple_of_row()`).

In [81]:
#Create augmented matrix A2_aug, composed of coefficient matrix A2, and RHS vector b2
A2_aug = A2.augment(b2, subdivide = true)

#Show matrix A2_aug
pretty_print("Augmented matrix [A2|b2] : ")
pretty_print(A2_aug)

#Perform Gaussian Elimination to obtain Row Echelon Form (stepwise operation)
#Firstly, from second row(inclusive) onwards, kill the non-zero elements in the first column of coefficient matrix A2, using ERO on first row of A2_aug
A2_aug.add_multiple_of_row(1, 0, -2)
A2_aug.add_multiple_of_row(2, 0, 3)
A2_aug.add_multiple_of_row(3, 0, -1)
pretty_print("Augmented matrix [A2|b2] (killed first column) : ")
pretty_print(A2_aug)

#Secondly, from third row(inclusive) onwards, kill the non-zero elements in the second column of coefficient matrix A2, using ERO on second row of A2_aug
A2_aug.add_multiple_of_row(2, 1, -7)
A2_aug.add_multiple_of_row(3, 1, -1)
pretty_print("Augmented matrix [A2|b2] (killed second column) : ")
pretty_print(A2_aug)

#From forth row(inclusive) onwards, the element in the third column of coefficient matrix A2 is already zero, no ERO is needed
#Show final REF
pretty_print("REF : ")
pretty_print(A2_aug)

#Solve the equations by back-substitution
ref_w = 15 / 3
ref_z = (238 - 26 * ref_w) / 18
ref_y = - 27 + 3 * ref_w + 2 * ref_z
ref_x = 13 - ref_w - ref_z - ref_y

#Show the results for x, y, z and w using Gaussian Elimination and Back-Substition
pretty_print("Results of Gaussian Elimination and Back-Substitution: ")
pretty_print("x = ", ref_x, ", y = ", ref_y, ", z = ", ref_z, ", w = ", ref_w)

marks += 3

'Augmented matrix [A2|b2] : '

[ 1  1  1  1|13]
[ 2  3  0 -1|-1]
[-3  4  1  2|10]
[ 1  2 -1  1| 1]

'Augmented matrix [A2|b2] (killed first column) : '

[  1   1   1   1| 13]
[  0   1  -2  -3|-27]
[  0   7   4   5| 49]
[  0   1  -2   0|-12]

'Augmented matrix [A2|b2] (killed second column) : '

[  1   1   1   1| 13]
[  0   1  -2  -3|-27]
[  0   0  18  26|238]
[  0   0   0   3| 15]

'REF : '

[  1   1   1   1| 13]
[  0   1  -2  -3|-27]
[  0   0  18  26|238]
[  0   0   0   3| 15]

'Results of Gaussian Elimination and Back-Substitution: '

'x = ' 2 ', y = ' 0 ', z = ' 6 ', w = ' 5

### 2(c)
<div style="text-align: right; font-size: 1.1em; color:red"> [1 mark]</div>

Use the built-in SageMath method `solve()` to solve the given system of linear equations. Verify that the solution is the same as you got in **2(b)**.

In [82]:
#Create equations for simultaneous substitution
var('x, y, z, w')
eq_1 = x + y + z + w == 13
eq_2 = 2*x + 3*y - w == -1
eq_3 = -3*x + 4*y + z + 2*w == 10
eq_4 = x + 2*y - z + w == 1
solve([eq_1, eq_2, eq_3, eq_4], x, y, z, w)

#Verify the results of Gaussian Elimination and Back-Substitution with built-in SageMath function
pretty_print("Results of Gaussian Elimination and Back-Substitution(2b): ")
pretty_print("x = ", ref_x, ", y = ", ref_y, ", z = ", ref_z, ", w = ", ref_w)

pretty_print("Results using SageMath:")
pretty_print(str(solve([eq_1, eq_2, eq_3, eq_4], x, y, z, w))[3:-3])

pretty_print("Hence, the results in 2(b) is the same as SageMath's computation.")

marks += 0.8
#can use == for verification

'Results of Gaussian Elimination and Back-Substitution(2b): '

'x = ' 2 ', y = ' 0 ', z = ' 6 ', w = ' 5

'Results using SageMath:'

'x == 2, y == 0, z == 6, w == 5'

"Hence, the results in 2(b) is the same as SageMath's computation."

### 2(d)
<div style="text-align: right; font-size: 1.1em; color:red"> [3 marks]</div>

Compute the ***LU decomposition*** for the matrix given below.
(Use only the method `matrix.add_multiple_of_row())`
$$ C_2 =  \left(\begin{array}{rr}
2 & 3 & 1 & 5 \\
6 & 13 & 5 & 19 \\
2 & 19 & 10 & 23 \\
4 & 10 & 11 & 31
\end{array}\right) $$

In [83]:
#Create matrix C2
C2 = matrix([[2, 3, 1, 5], [6, 13, 5, 19], [2, 19, 10, 23], [4, 10, 11, 31]])

#Make a copy of C2, name it as U and perform Gaussian Elimination on U
U = copy(C2)
pretty_print("U before Gaussian Elimination :")
pretty_print(U)

#Perform Gaussian Elimination
#Firstly, from second row(inclusive) onwards, kill the non-zero elements in the first column of matrix U, using ERO on first row of matrix U
U.add_multiple_of_row(1, 0, -3)
U.add_multiple_of_row(2, 0, -1)
U.add_multiple_of_row(3, 0, -2)
pretty_print("Matrix U (killed first column) : ")
pretty_print(U)

#Secondly, from third row(inclusive) onwards, kill the non-zero elements in the second column of matrix U, using ERO on second row of matrix U
U.add_multiple_of_row(2, 1, -4)
U.add_multiple_of_row(3, 1, -1)
pretty_print("Matrix U (killed second column) : ")
pretty_print(U)

#Thirdly, from forth row(inclusive) onwards, kill the non-zero elements in the third column of matrix U, using ERO on third row of matrix U
U.add_multiple_of_row(3, 2, -7)
pretty_print("Matrix U after Gaussian Elimination :")
pretty_print(U)

#Since det(U) is non-zero (diagonal are all non-zero elements, it has an inverse)
#Hence, we can get L by taking matrix C2 multiplied by inverse of matrix U
L = C2 * U.inverse()

#Show the results
pretty_print("We have the final results: ")
pretty_print("U :", U, "L :", L)

marks += 1.8

# don't use inverse to find L

'U before Gaussian Elimination :'

[ 2  3  1  5]
[ 6 13  5 19]
[ 2 19 10 23]
[ 4 10 11 31]

'Matrix U (killed first column) : '

[ 2  3  1  5]
[ 0  4  2  4]
[ 0 16  9 18]
[ 0  4  9 21]

'Matrix U (killed second column) : '

[ 2  3  1  5]
[ 0  4  2  4]
[ 0  0  1  2]
[ 0  0  7 17]

'Matrix U after Gaussian Elimination :'

[2 3 1 5]
[0 4 2 4]
[0 0 1 2]
[0 0 0 3]

'We have the final results: '

'U :' [2 3 1 5]
[0 4 2 4]
[0 0 1 2]
[0 0 0 3] 'L :' [1 0 0 0]
[3 1 0 0]
[1 4 1 0]
[2 1 7 1]

### 2(e)
<div style="text-align: right; font-size: 1.1em; color:red"> [2 marks]</div>

Calculate the determinant of $C_2$ using $L$ and $U$ matrices. Verify that the value is the same when calculated using built-in Sagemath method.(Use the built-in SageMath method `matrix.det()`)

In [84]:
# Computation of C2's determinant from multiplying the diagonal elemnents of U as it is a Upper Triangular Matrix
det_C2 = 2 * 4 * 1 * 3

#Verify the value of C2's determinant using built-in SageMath function
pretty_print("Result of computation of C2's determinant using L and U matrices : ", det_C2)
pretty_print("Result of C2's determinant using built-in SageMath function : ", C2.det())
pretty_print("Is result in 2(e) equals to SageMath's computation? :", det_C2 == C2.det())

marks += 2

"Result of computation of C2's determinant using L and U matrices : " 24

"Result of C2's determinant using built-in SageMath function : " 24

"Is result in 2(e) equals to SageMath's computation? :" True

<div style="color:darkgreen;background-color:lightgreen;padding:10px">


# Question 3
<div style="text-align: right; font-size: 1.3em; color:red"> Total 20 Marks for Q3</div>
</div>

Work with the system of linear equations $A_3x = b_3$ below to answer the questions that follow.
$$ \begin{array}{rr4}
 2 \, x + y + 2 \, z + w &=& 6\\
 6 \, x - 6 \, y + 6 \, z + 12 \, w &=& 36\\
 4 \, x + 3 \, y + 3 \, z - 3 \, w &=& -1\\
 2 \, x + 2 \, y - z + w &=& 10
\end{array}$$
`Eqns: 
 2*x + y+ 2*z + w == 6,
 6*x - 6*y + 6*z + 12*w == 36,
 4*x + 3*y + 3*z -3*w == -1,
 2*x + 2*y -z + w == 10`

### 3(a)
<div style="text-align: right; font-size: 1.1em; color:red"> [3 marks]</div>

Find the inverse of coefficient matrix ($A_3$) using Gauss-Jordan method. Show the steps using `A3.add_multiple_of_row()`.

In [85]:
#Create matrix A3
A3 = matrix(QQ, [[2, 1, 2, 1], [6, -6, 6, 12], [4, 3, 3, -3], [2, 2, -1, 1]])

#Create Identity matrix of 4 by 4
I = identity_matrix(4)

#Create Augmented matrix [A3|I]
A3_I_aug = A3.augment(I, subdivide = true)
pretty_print("Matrix [A3|I] (Before Gauss-Jordan Elimination) : ")
pretty_print(A3_I_aug)

#Perform Gauss-Jordan Elimination
#Start with Gaussian Elimination
#Firstly, from second row(inclusive) onwards, kill the non-zero elements in the first column of matrix A3, using ERO on first row of matrix A3_I_aug
A3_I_aug.add_multiple_of_row(1, 0, -3)
A3_I_aug.add_multiple_of_row(2, 0, -2)
A3_I_aug.add_multiple_of_row(3, 0, -1)
pretty_print("Matrix [A3|I] (killed first column) : ")
pretty_print(A3_I_aug)

#Secondly, from third row(inclusive) onwards, kill the non-zero elements in the second column of matrix A3, using ERO on second row of matrix A3_I_aug
A3_I_aug.add_multiple_of_row(2, 1, 1/9)
A3_I_aug.add_multiple_of_row(3, 1, 1/9)
pretty_print("Matrix [A3|I] (killed second column) : ")
pretty_print(A3_I_aug)

#Thirdly, from forth row(inclusive) onwards, kill the non-zero elements in the third column of matrix A3, using ERO on third row of matrix A3_I_aug
A3_I_aug.add_multiple_of_row(3, 2, -3)
pretty_print("Matrix [A3|I] after Gaussian Elimination :")
pretty_print(A3_I_aug)

#Perform Scaling to make all diagonal elements 1's and kill the non-zero elements of upper triangular from bottom upwards

#Scale the forth row's diagonal to 1
A3_I_aug.add_multiple_of_row(3, 3, -12/13)
#From third row(inclusive) backwards(from bottom), kill the non-zero elements in the forth column of matrix A3, using ERO on forth row of matrix A3_I_aug
A3_I_aug.add_multiple_of_row(2, 3, 4)
A3_I_aug.add_multiple_of_row(1, 3, -9)
A3_I_aug.add_multiple_of_row(0, 3, -1)
pretty_print("Matrix [A3|I] (scaled forth row's diagonal and killed forth column) :")
pretty_print(A3_I_aug)

#Scale the third row's diagonal to 1
A3_I_aug.add_multiple_of_row(2, 2, -2)
#From second row(inclusive) backwards(from bottom), kill the non-zero elements in the third column of matrix A3, using ERO on third row of matrix A3_I_aug
A3_I_aug.add_multiple_of_row(0, 2, -2)
pretty_print("Matrix [A3|I] (scaled third row's diagonal and killed third column) :")
pretty_print(A3_I_aug)

#Scale the second row's diagonal to 1
A3_I_aug.add_multiple_of_row(1, 1, -10/9)
#From first row(inclusive) backwards(from bottom), kill the non-zero elements in the second column of matrix A3, using ERO on second row of matrix A3_I_aug
A3_I_aug.add_multiple_of_row(0, 1, -1)
pretty_print("Matrix [A3|I] (scaled second row's diagonal and killed second column) :")
pretty_print(A3_I_aug)

#Scale the first row's diagonal to 1
A3_I_aug.add_multiple_of_row(0, 0, -1/2)
pretty_print("Matrix [A3|I] (scaled first row's diagonal) :")
pretty_print(A3_I_aug)

#Show the final [A3|I] after Gauss-Jordan Elimination
pretty_print("Matrix [A3|I] after Gauss-Jordan Elimination :")
pretty_print(A3_I_aug)
pretty_print("Hence, the inverse of A3 is on the right of RREF of [A3|I] after Gauss-Jordan Elimination :")

#Create the inverse matrix A3^-1
A3_inv_GJ = A3_I_aug.submatrix(0,4,4,4)
pretty_print(A3_inv_GJ)

marks += 3

'Matrix [A3|I] (Before Gauss-Jordan Elimination) : '

[ 2  1  2  1| 1  0  0  0]
[ 6 -6  6 12| 0  1  0  0]
[ 4  3  3 -3| 0  0  1  0]
[ 2  2 -1  1| 0  0  0  1]

'Matrix [A3|I] (killed first column) : '

[ 2  1  2  1| 1  0  0  0]
[ 0 -9  0  9|-3  1  0  0]
[ 0  1 -1 -5|-2  0  1  0]
[ 0  1 -3  0|-1  0  0  1]

'Matrix [A3|I] (killed second column) : '

[   2    1    2    1|   1    0    0    0]
[   0   -9    0    9|  -3    1    0    0]
[   0    0   -1   -4|-7/3  1/9    1    0]
[   0    0   -3    1|-4/3  1/9    0    1]

'Matrix [A3|I] after Gaussian Elimination :'

[   2    1    2    1|   1    0    0    0]
[   0   -9    0    9|  -3    1    0    0]
[   0    0   -1   -4|-7/3  1/9    1    0]
[   0    0    0   13|17/3 -2/9   -3    1]

"Matrix [A3|I] (scaled forth row's diagonal and killed forth column) :"

[     2      1      2      0| 22/39  2/117   3/13  -1/13]
[     0     -9      0      0|-90/13  15/13  27/13  -9/13]
[     0      0     -1      0|-23/39  5/117   1/13   4/13]
[     0      0      0      1| 17/39 -2/117  -3/13   1/13]

"Matrix [A3|I] (scaled third row's diagonal and killed third column) :"

[     2      1      0      0| -8/13   4/39   5/13   7/13]
[     0     -9      0      0|-90/13  15/13  27/13  -9/13]
[     0      0      1      0| 23/39 -5/117  -1/13  -4/13]
[     0      0      0      1| 17/39 -2/117  -3/13   1/13]

"Matrix [A3|I] (scaled second row's diagonal and killed second column) :"

[     2      0      0      0|-18/13   3/13   8/13   6/13]
[     0      1      0      0| 10/13  -5/39  -3/13   1/13]
[     0      0      1      0| 23/39 -5/117  -1/13  -4/13]
[     0      0      0      1| 17/39 -2/117  -3/13   1/13]

"Matrix [A3|I] (scaled first row's diagonal) :"

[     1      0      0      0| -9/13   3/26   4/13   3/13]
[     0      1      0      0| 10/13  -5/39  -3/13   1/13]
[     0      0      1      0| 23/39 -5/117  -1/13  -4/13]
[     0      0      0      1| 17/39 -2/117  -3/13   1/13]

'Matrix [A3|I] after Gauss-Jordan Elimination :'

[     1      0      0      0| -9/13   3/26   4/13   3/13]
[     0      1      0      0| 10/13  -5/39  -3/13   1/13]
[     0      0      1      0| 23/39 -5/117  -1/13  -4/13]
[     0      0      0      1| 17/39 -2/117  -3/13   1/13]

'Hence, the inverse of A3 is on the right of RREF of [A3|I] after Gauss-Jordan Elimination :'

[ -9/13   3/26   4/13   3/13]
[ 10/13  -5/39  -3/13   1/13]
[ 23/39 -5/117  -1/13  -4/13]
[ 17/39 -2/117  -3/13   1/13]

### 3(b)
<div style="text-align: right; font-size: 1.1em; color:red"> [2 marks]</div>

Find the adjoint matrix of $A_3$ and calculate $A_3^{-1}$ using it. Compare with your results in $3(a)$

In [86]:
#Create the adjoint matrix of A3
A3_adj = A3.adjugate()

#Compute the inverse of A3 using its adjoint matrix, i.e., taking (1/(det(A3))) * A3_adj
A3_inv_adj = 1/A3.det() * A3_adj

#Show the result of computation of A3^-1 using its adjugate matrix in 3(b)
pretty_print("Inverse of A3 using adjoint matrix in 3(b):")
pretty_print(A3_inv_adj)

#Compare the result of computation of inverse of A3 using Gauss-Jordan Elimination method in 3(a)
pretty_print("Inverse of A3 using Gauss-Jordan method in 3(a):")
pretty_print(A3_inv_GJ)
pretty_print("Is result in 3(b) equals to 3(a)? :", A3_inv_adj == A3_inv_GJ)

marks += 2

'Inverse of A3 using adjoint matrix in 3(b):'

[ -9/13   3/26   4/13   3/13]
[ 10/13  -5/39  -3/13   1/13]
[ 23/39 -5/117  -1/13  -4/13]
[ 17/39 -2/117  -3/13   1/13]

'Inverse of A3 using Gauss-Jordan method in 3(a):'

[ -9/13   3/26   4/13   3/13]
[ 10/13  -5/39  -3/13   1/13]
[ 23/39 -5/117  -1/13  -4/13]
[ 17/39 -2/117  -3/13   1/13]

'Is result in 3(b) equals to 3(a)? :' True

### 3(c)
<div style="text-align: right; font-size: 1.1em; color:red"> [2 marks]</div>


Using $A_3^{-1}$ (from **3(a)** or **3(b)**), solve the system of linear equations.


In [87]:
#Create the RHS vector b
b3 = vector([6, 36, -1, 10])

#A3x = b3, x = A3^-1 * b3, solve x using answer from 3(b)
x = A3_inv_adj * b3

#Show the components of vector x
pretty_print(x)

marks += 2

(2, 1, -1, 3)

Therefore, the value for each component of vector x is $x = 2, y = 1, z = -1, w = 3$

### 3(d)
<div style="text-align: right; font-size: 1.1em; color:red"> [1 mark]</div>

Compare your answer to the one from *SageMath* directly. (Use *SageMath built-in* method to compute inverse and use it to solve equations)

In [88]:
marks += 0.5

#Compare the result3(c) with SageMath's built-in .inverse() function
x_sm = A3.inverse() * b3
pretty_print("Result of x using inverse computed from adjugate matrix of A3 :", x)
pretty_print("Result of x using SageMath's function : ",x_sm)
#pretty_print("Is result in 3(c) same as SageMath's computation? :", x == x_sm1)
# compilation error in above line


'Result of x using inverse computed from adjugate matrix of A3 :' (2, 1, -1, 3)

"Result of x using SageMath's function : " (2, 1, -1, 3)

### 3(e)
<div style="text-align: right; font-size: 1.1em; color:red"> [3 marks]</div>

Use **Cramer's Rule** to solve the system of linear equations above.

In [89]:
#Show A3 and b3 for reference
pretty_print("A3 :", A3, " b3 :", b3)

#Cramer's Rule
#Create a list for holding the results of computation
cramer_sol = []

#Create a list for holding the x's elements' names (printing purposes)
names = ["x", "y", "z", "w"]

#To compute the value for x, replace the first column vector in A3 with b3, divide the determinant of A3_1 by determinant of A3
#To compute the value for y, replace the second column vector in A3 with b3, divide the determinant of A3_2 by determinant of A3
#To compute the value for z, replace the third column vector in A3 with b3, divide the determinant of A3_3 by determinant of A3
#To compute the value for w, replace the forth column vector in A3 with b3, divide the determinant of A3_4 by determinant of A3

#The four repetitive steps show above can be implemented using a for loop as below

#The for loop executes 4 times (1 to 4 inclusive)
for i in range(1,5):
    #Create a temporary matrix that is same as A3  
    A3_i = copy(A3)
    
    #Replace the i-th column of A3_i with column vector b3
    A3_i[:,i-1] = b3
    
    #Compute the solution and append it to sol
    cramer_sol.append(A3_i.det() / A3.det())
    
    #Show the results of x, y, z, w
    pretty_print('Replacing the column %d of A3 with b3. Solution for %s : %d' % (i, names[i-1], cramer_sol[i-1]))
    pretty_print(A3_i)

#Create the vector x of A3x = b3
x = vector([cramer_sol[0], cramer_sol[1], cramer_sol[2], cramer_sol[3]])

#Show vector x
pretty_print("x of A3x = b3 :", x)

marks += 3

'A3 :' [ 2  1  2  1]
[ 6 -6  6 12]
[ 4  3  3 -3]
[ 2  2 -1  1] ' b3 :' (6, 36, -1, 10)

'Replacing the column 1 of A3 with b3. Solution for x : 2'

[ 6  1  2  1]
[36 -6  6 12]
[-1  3  3 -3]
[10  2 -1  1]

'Replacing the column 2 of A3 with b3. Solution for y : 1'

[ 2  6  2  1]
[ 6 36  6 12]
[ 4 -1  3 -3]
[ 2 10 -1  1]

'Replacing the column 3 of A3 with b3. Solution for z : -1'

[ 2  1  6  1]
[ 6 -6 36 12]
[ 4  3 -1 -3]
[ 2  2 10  1]

'Replacing the column 4 of A3 with b3. Solution for w : 3'

[ 2  1  2  6]
[ 6 -6  6 36]
[ 4  3  3 -1]
[ 2  2 -1 10]

'x of A3x = b3 :' (2, 1, -1, 3)

### 3(f)
<div style="text-align: right; font-size: 1.1em; color:red"> [2 marks]</div>

Solve the system of linear equations again using `solve()` and compare with your answers in **3(e)**.

In [90]:
#Create equations for simultaneous substitution
var('x, y, z, w')
eq_1 = 2*x + y + 2*z + w == 6
eq_2 = 6*x - 6*y + 6*z + 12*w == 36
eq_3 = 4*x + 3*y + 3*z - 3*w == -1
eq_4 = 2*x + 2*y - z + w == 10
solve([eq_1, eq_2, eq_3, eq_4], x, y, z, w)

#Verify the results of x, y, z, w in x of A3x = b using Cramer's Rule with that using built-in SageMath function
pretty_print("The elements of x computed using Cramer's Rule 3(e) :")
pretty_print("x = ", cramer_sol[0], ", y = ", cramer_sol[1], ", z = ", cramer_sol[2], ", w = ", cramer_sol[3])

pretty_print("The elements of x computed using SageMath 3(f) :")
pretty_print(str(solve([eq_1, eq_2, eq_3, eq_4], x, y, z, w))[3:-3])

pretty_print("The results in 3(e) is same as SageMath's solution in 3(f)")

marks += 1.6

#can do comparison using ==

"The elements of x computed using Cramer's Rule 3(e) :"

'x = ' 2 ', y = ' 1 ', z = ' -1 ', w = ' 3

'The elements of x computed using SageMath 3(f) :'

'x == 2, y == 1, z == -1, w == 3'

"The results in 3(e) is same as SageMath's solution in 3(f)"

### 3(g)
<div style="text-align: right; font-size: 1.1em; color:red"> [2 marks]</div>

Can you find one vector $b_3$ (the RHS) for which the system becomes unsolvable? If not, why not?

In [91]:
#Show the rank of coefficient matrix A3
pretty_print("Rank of coefficient matrix A3 :", A3.rank())

marks += 2

'Rank of coefficient matrix A3 :' 4

Since matrix A3 is a full-rank matrix (rank of 4 and A3 is a 4 by 4 matrix), it is impossible to have a b3 that makes the system unsolvable. This is because the inconsistent condition will never occurs, i.e., a row with 0 = b in RREF form.

### 3(h)
<div style="text-align: right; font-size: 1.1em; color:red"> [2 marks]</div>

Here is another matrix $C_3$
$$ C_3 =  \left(\begin{array}{rr}
1 & 0 & 0 & 2\\
0 & -1 & 1 & 4
\end{array}\right) $$

Calculate $C_3^{-1}$ 

Since C3 is not a square matrix, it is guaranteed that C3 does not have an inverse.

# can find right inverse


In [92]:
#Verify the answer statement in 3(h) with SageMath built-in function
C3 = matrix([[1, 0, 0, 2], [0, -1, 1, 4]])



try:
    C3_inv = C3.inverse()
    pretty_print("The answer statement is incorrect. C3 has an inverse. The inverse is :", C3_inv)
except Exception as excpt:
    pretty_print("The answer statement is correct. C3 does not have an inverse.")
    
    

'The answer statement is correct. C3 does not have an inverse.'

### 3(i)
<div style="text-align: right; font-size: 1.1em; color:red"> [2 marks]</div>

Calculate $(C_3^T)^{-1}$

Since C3 is a wide matrix (and not a square matrix), the transpose of C3 is a tall matrix, so it is guaranteed that the transpose does not have an inverse.

# can find left inverse

In [93]:
#Verify the answer statement in 3(i) with SageMath built-in function
try:
    C3_T_inv = (C3.T).inverse()
    pretty_print("The answer statement is incorrect. Transpose of C3 has an inverse. The inverse is :", C3_T_inv)
except Exception as excpt:
    pretty_print("The answer statement is correct. Transpose of C3 does not have an inverse.")

'The answer statement is correct. Transpose of C3 does not have an inverse.'

### 3(j)
<div style="text-align: right; font-size: 1.1em; color:red"> [1 mark]</div>

Is $C_3$ a rank deficient matrix? Are the column vectors of $C_3$ linearly independent? If not, why?

In [94]:
#Show the rank of C3
pretty_print("Rank(C3) :", C3.rank())

'Rank(C3) :' 2

C3 is not a rank deficient matrix, in fact, C3, as a 2 by 4 matrix is a full-rank (full-row-rank) matrix.

The column vectors of C3 are guaranteed to be linearly dependent because C3 is not full column rank. This implies that there are only 2 column vectors are linearly independent of each other, the other two column vectors are linear combinations of the first two column vectors.

In [95]:
marks += 1
print(marks)


#For example, let's name the column vectors of C3, from left to right, as c1, c2, c3 and c4.
c1 = C3 * vector([1, 0, 0, 0])
c2 = C3 * vector([0, 1, 0, 0])
c3 = C3 * vector([0, 0, 1, 0])
c4 = C3 * vector([0, 0, 0, 1])

test1 = 2 * c1 + 4 * c3 == c4
test2 = 0 * c1 - 1 * c3 == c2

#Verify the results
if(test1 and test2):
    pretty_print("2 * c1 + 4 * c3 = c4 is true")
    pretty_print("0 * c1 - 1 * c3 = c2 is true")
    
    

33.5000000000000


'2 * c1 + 4 * c3 = c4 is true'

'0 * c1 - 1 * c3 = c2 is true'

<div style="color:white;background-color:red;padding:5px">


### <center>End of Assignment 1</center>
</div>